### ISSUE TITLE
Error installing changesPlugin

### ISSUE THREAD

**Issue by jikk** [chrisbra/changesPlugin#13]
I tried to install changesPlugin and I'm using pathogen but I've encountered the following error. 
Do you have any idea how to resolve it?

```
% vim ~/.vimrc
Error detected while processing /Users/kjee/.vim/bundle/changesPlugin/plugin/changesPlugin.vim:
line   80:
E227: mapping already exists for <nowait>
```

Thanks a lot for your help!

**Comment by chrisbra** [comment]
What is your Vim version?

**Comment by jikk** [comment]
version 7.3 running from os x 10.10.2

**Comment by chrisbra** [comment]
Please check current head. Should be fixed now.
