### ISSUE TITLE
Error 'Vim(if):E121: Undefined variable: s:signcolumn`

### ISSUE THREAD

**Issue by khingblue** [chrisbra/changesPlugin#16]
I installed the plugin for my vim 7.4, without any options defined.

Anytime when I open a file, there is error on status bar: `Vim(if):E121: Undefined variable: s:signcolumn`

Any idea how to fix it? Thanks.

**Comment by khingblue** [comment]
That's so quick, thanks @chrisbra !

**Comment by chrisbra** [comment]
Hi khingblue!

On Do, 08 Sep 2016, khingblue wrote:

> That's so quick, thanks @chrisbra !

no problem.
