### ISSUE TITLE
ChangesSignTextDummyCh question

### ISSUE THREAD

**Issue by aq2** [chrisbra/changesPlugin#20]
Hi, thanks for your useful plugin!

I've successfully configured my own colours, but what are the ChangesSignTextDummyCh and ChangesSignTextDummyAdd highlight groups for?

**Comment by chrisbra** [comment]
Here is an example:
![grafik](https://user-images.githubusercontent.com/244927/57321886-8f538700-7102-11e9-8764-2eecb7e888e8.png)

If you change many lines, you have several lines with the `+` highlighting. So the first `+` line, will be `ChangesSignTextAdd` and all the following lines will have `ChangesSignTextDummyAdd`, so from the example above, if I enter

    hi ChangesSignTextDummyAdd guifg=blue

The screenshot will change to:
![grafik](https://user-images.githubusercontent.com/244927/57322043-ee190080-7102-11e9-9776-57b93af178ba.png)

**Comment by aq2** [comment]
very clear explanation

danke schön
