### ISSUE TITLE
override key mapping

### ISSUE THREAD

**Issue by aq2** [chrisbra/changesPlugin#21]
I have leader-hl mapped to :nohl, so your leader-h mapping interferes with this.

I've worked out a horribly hacky way of overriding this:

    nnoremap <Leader>hl :nohl<CR>
    nunmap <Leader>hl
    autocmd VimEnter * nnoremap <leader>hl :nohl<CR>

This works fine when I first start vim, but breaks if I need to reload any vimrc files

I've read elsewhere that I could use an  /after/plugin folder to make my mapping work after your plugin loads.

Or is there some hidden option that I could change to disable your mapping?

Or any other method?

Thanks again.

**Comment by chrisbra** [comment]
okay, should be fixed now. The plugin now checks, that the keys are available and not yet mapped.

**Comment by aq2** [comment]
hi, i've updated the plugin, but my problem still remains - although i have found a work-around

i'm not skilled in vimscript, but I think your new commit checks for a current leader-h mapping, but not leader-h* and my problem is i have leader-hl, so your leader-h is still triggered first.

as a workaround, i have now also mapped leader-h

**thanks** for your help and plugin, and may i suggest you add options in the plugin to disable or change remaps?

**Comment by chrisbra** [comment]
ah, that is indeed the problem. Try remapping the `<Plug>(ChangesStageHunk)` to something you don't need or want:

    nmap     <silent> <Nop> <Plug>(ChangesStageHunk)

So the plugin thinks the functionality is already mapped and won't try to map it to `<Leader>h`.

**Comment by aq2** [comment]
that sounds like a plan, man

no problems now  :+1:
