### ISSUE TITLE
vim-airline conflicts with changesPlugin

### ISSUE THREAD

**Issue by Mishail** [chrisbra/changesPlugin#23]
From https://github.com/vim-airline/vim-airline/issues/2107

#### environment

- vim: MacVim Snapshot 162 (Vim patch 8.2.319)
- vim-airline: 
  * vim-airline/vim-airline@185bcc5e886e424e827d20eef762458a7ea4dede - doesn't have the problem
  * vim-airline/vim-airline@74ca43a9b66a8fa6c01c3d7c51bbb034622eedf2 and later has the problem

- What is your airline configuration: 
```
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
```
if you are using Neovim:
- does it happen in Vim: NO. Everything works in Neovim (I'm using VimR)

#### actual behavior

If I start vim with `changesPlugin` plugin enabled, then the cursor gets stuck in the top leftmost corner, blinking as a mad, and it's not possible to move it or to do anything.

So I either have to disable the `changesPlugin` or to pin airline to vim-airline/vim-airline@185bcc5e886e424e827d20eef762458a7ea4dede

Here is the configuration for the `changesPlugin`
```
let g:changes_use_icons=0
let g:changes_linehi_diff=1
```

**Comment by chrisbra** [comment]
This only happens with mac vim but not with terminal vim? If you back out the last commit and go back to 6bf2c356875dffc61f27fac24fdcdc2d11f14554 does it work?

**Comment by Mishail** [comment]
> This only happens with mac vim but not with terminal vim? 

It happens for terminal vim as well, both for the one from MacVim and the default one.
```VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 29 2020 00:47:39)
macOS version
Included patches: 1-503, 505-680, 682-2292
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
```

>  If you back out the last commit and go back to 6bf2c35 does it work?

Yes, it does. I don't see the problem with 6bf2c35

**Comment by chrisbra** [comment]
okay, I reverted that commit. Seems like it was a bad idea.

**Comment by Mishail** [comment]
thanks!
