### ISSUE TITLE
changesPlugin forces signcolumn to be shown, even in terminal mode

### ISSUE THREAD

**Issue by andrewferrier** [chrisbra/changesPlugin#24]
With NVIM v0.5.0-d46c400 (although I think/assume this applies to regular Vim, and other versions), I find that changesPlugin always forces the `signcolumn` to be shown (i.e. extra characters to the left of the buffer), even for terminal buffers. For terminal buffers, I would argue that changesPlugin is basically irrelevant; they are constantly changing, and have no saved state, so changesPlugin should probably be ignoring them.

I've put a workaround into my own fork of changesPlugin: https://github.com/andrewferrier/changesPlugin/commit/2f0d82d911adaac4aff9d1f6e2546195961323d6. It's probably not the most elegant, but it would be great if you could incorporate something like this into changesPlugin itself.

Thanks for all your work on this great plugin, I find it really helpful!

**Comment by chrisbra** [comment]
Thanks, looks good.

**Comment by chrisbra** [comment]
Can you please create a PR for that?

**Comment by andrewferrier** [comment]
Done; see https://github.com/chrisbra/changesPlugin/pull/25.

**Comment by andrewferrier** [comment]
Closing as merged.
