### ISSUE TITLE
g:changes_linehi_diff - wont initalize correctly

### ISSUE THREAD

**Issue by JoseConseco** [chrisbra/changesPlugin#27]
If I understand correctly enabling changes_linehi_diff  will switch to second changes higlight style - where it higlight whole line, but it seems to not work for me.
I can use 'CT' - to jump to next change style mode, but it would be cool if  user could setup line highlight as default style mode.

Also option to disable left column signs would be cool  (right now they override gitsigns plugin plug markers) .  Cool pluging @chrisbra

**Comment by chrisbra** [comment]
It was most likely not completely working, because the `'[` and `']` where the same (can happen when deleting a line). I made some slight changes to still highlight in that case
